Use new metadata API
qooxdoo/qx-cli pull request #60
Opened 2017-12-06 16:43 UTC by cboulanger

2017-12-06 16:48 UTC, hkollmann submitted a review, later dismissed

2017-12-07 07:55 UTC, cboulanger commented
@johnspackman Can you review and merge if you approve of the PR?

2017-12-07 10:07 UTC, hkollmann commented
I think we can remove getQoodooVersion instead of deprecate it, could‘nt we?

2017-12-07 11:00 UTC, johnspackman requested changes

2017-12-07 11:00 UTC, johnspackman commented on lib/qxcli/commands/Command.js
> +     * @deprecated Use {@link #getUserQxVersion} instead.
I agree with @hkollmann there's no need to deprecate at this stage, we're still officially in beta and the API is allowed to change without warning.

2017-12-07 12:37 UTC, hkollmann commented
In this case you must chance template_vars.js, line 69 too!

2017-12-07 13:44 UTC, cboulanger commented
I tried to remove the method and there was a problem which I did not have the time to investigate - that's why I left it and deprecated it for the time being. I agree with you and will have a second look hopefully later today.

2017-12-09 16:39 UTC, cboulanger commented
@hkollmann @johnspackman Ok, I have reworked it so that now the version number is no longer taken from the `versions.txt` file but from the Manifest.json (as it should be). For this to work, you need the newest master with  @hkollmann's PR that bumped the version numbers (otherwise it the version is still `5.1`, which is invalid semver in any case).

2017-12-09 18:39 UTC, hkollmann approved these changes

2017-12-10 19:42 UTC, cboulanger commented
@johnspackman can you review so that this can get merged? Thanks!

2017-12-11 06:45 UTC, johnspackman approved these changes

2017-12-11 06:46 UTC, merged